Update

diff --git a/.github/workflows/dispatch.yml b/.github/workflows/dispatch.yml
--- a/.github/workflows/dispatch.yml
+++ b/.github/workflows/dispatch.yml
@@ -14,6 +14,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Validate version format
+        id: validate_version
+        run: |
+          if ! [[ "${{ github.event.inputs.new_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format. Must follow Semantic Versioning (e.g., 1.0.0)."
+            exit 1
+          fi
+
       - name: Check if version already exists
         id: check_version
         run: |
@@ -34,7 +42,7 @@ jobs:
         run: |
           git config --global user.name 'github-actions'
           git config --global user.email 'github-actions@github.com'
-          git add docs/antora.yml package.json
+          git add docs/antora.yml package.json package-lock.json
           git commit -m "Update version to ${{ github.event.inputs.new_version }}"
           git tag ${{ github.event.inputs.new_version }}
           git push origin --tags
